
-- Libray Schema

-- Create Table Books
CREATE TABLE AUTHORS(
AUTHOR_ID INT PRIMARY KEY NOT NULL,
AUTHOR_NAME VARCHAR(30) NOT NULL,
BIRTH_YEAR INT NOT NULL
);


-- Create Table Publisher
CREATE TABLE PUBLISHER(
PUBLISHER_ID INT PRIMARY KEY NOT NULL,
PUBLISHER_NAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL
);

-- Create Table Books

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY NOT NULL,
TITLE VARCHAR(30) NOT NULL,
AUTHOR_ID INT,
PUBLISHER_ID INT,
GENRE VARCHAR(20),
TOTAL_COPIES INT NOT NULL,
AVAILABLE_COPIES INT NOT NULL,

FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
FOREIGN KEY(PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID)
);

-- Create Table Members

CREATE TABLE MEMBERS(
MEMBER_ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PHONE_NO VARCHAR(10) NOT NULL,
MEMBERSHIP_DATE DATE NOT NULL,
STATUS VARCHAR(20)
);

-- Create Table Book_Issued

CREATE TABLE BOOK_ISSUED(

ISSUE_ID INT PRIMARY KEY NOT NULL,
BOOK_ID INT,
MEMBER_ID INT,
ISSUE_DATE DATE NOT NULL,
DUE_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL,

FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

